### ISSUE TITLE
Configuração base

### ISSUE THREAD

**Issue by ryanolivrdev** [geta-org/seen-mobile#6]
## Overview 
 - Nessa tarefa deve ser configurando o tema do native base usando a fonte, typography e cores do protótipo do figma.

## TODO
- [x] Configurar provider do native base na pasta de Contexts.
- [x] Configurar fontes da google usando o Expo fontes.
- [x] Fazer estado de loading das fontes usando o Expo fontes.
- [x] Configurar Typography.
- [x] Configurar Cores usando o padrão do Native base.

## Docs
 - https://docs.nativebase.io/default-theme
